### ISSUE TITLE
[BUG] importing into vercel

### ISSUE THREAD

**Issue by mogaffar** [nmelhado/league-page#67]
this new update wouldnt let me update the fork so i had to delete everything and re do it all. When i try to redo the site thru vercel it gives me this error when its building/importing the repo.

14:59:44.243
> league-page@1.1.1 build /vercel/path0
14:59:44.243
> svelte-kit build
14:59:44.243
14:59:44.660
vite v2.5.7 building for production...
14:59:44.815
transforming...
14:59:48.028
✓ 43 modules transformed.
14:59:48.028
[rollup-plugin-dynamic-import-variables] Unexpected token (4:36)
14:59:48.028
file: /vercel/path0/src/lib/utils/leagueInfo.js:4:36
14:59:48.029
> Unexpected token (4:36)
14:59:48.031
SyntaxError: Unexpected token (4:36)
14:59:48.031
    at Parser.pp$4.raise (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:16958:13)
14:59:48.031
    at Parser.pp.unexpected (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14466:8)
14:59:48.031
    at Parser.pp.semicolon (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14443:64)
14:59:48.031
    at Parser.pp$1.parseExpressionStatement (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14924:8)
14:59:48.031
    at Parser.pp$1.parseStatement (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14659:24)
14:59:48.031
    at Parser.pp$1.parseTopLevel (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14523:21)
14:59:48.031
    at Parser.parse (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14315:15)
14:59:48.032
    at Function.parse (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:14346:35)
14:59:48.032
    at Graph.contextParse (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:20344:38)
14:59:48.032
    at Object.transform (/vercel/path0/node_modules/vite/dist/node/chunks/dep-63d4bd14.js:43069:27)
14:59:48.046
npm ERR! code ELIFECYCLE
14:59:48.046
npm ERR! errno 1
14:59:48.050
npm ERR! league-page@1.1.1 build: `svelte-kit build`
14:59:48.050
npm ERR! Exit status 1
14:59:48.050
npm ERR! 
14:59:48.050
npm ERR! Failed at the league-page@1.1.1 build script.
14:59:48.050
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
14:59:48.062
14:59:48.062
npm ERR! A complete log of this run can be found in:
14:59:48.062
npm ERR!     /vercel/.npm/_logs/2021-09-13T18_59_48_051Z-debug.log
14:59:48.083
Error: Command "npm run build" exited with 1

**Comment by nmelhado** [comment]
You made a mistake in your leagueInfo file. Replace line 4 and 5 with the following:

```
export const dues = 100; // (optional) used in template constitution page
export const dynasty = false; // true for dynasty leagues, false for redraft and keeper
export const enableBlog = false; // requires VITE_CONTENTFUL_ACCESS_TOKEN and VITE_CONTENTFUL_SPACE environment variables

```

**Comment by nmelhado** [comment]
If that fixes it, let me know and I'll close the issue!

**Comment by mogaffar** [comment]
that fixed it thanks.
